#!/usr/bin/env bash
set -euo pipefail

# generate-schema-descriptions.sh - Call LLM API to generate schema descriptions
#
# Designed for CI/CD pipelines where no interactive LLM session is available.
# Reads the describe-prompt.json generated by db-schema-sync.sh --describe
# and produces descriptions.json for the sync step.
#
# Usage:
#   ~/.claude/scripts/generate-schema-descriptions.sh [options]
#
# Options:
#   --snapshot-dir <dir>   Snapshot directory (default: /tmp/db-schema-sync)
#   --provider <name>      API provider: anthropic, github (default: auto-detect)
#   --model <model>        Model ID (default: from PROJECT.yaml)
#   --max-tokens <n>       Max response tokens (default: 4096)
#   --dry-run              Print prompt but don't call API
#
# Providers:
#   anthropic  - Anthropic Messages API (requires ANTHROPIC_API_KEY)
#   github     - GitHub Models via Azure AI inference (uses GITHUB_TOKEN, free in Actions)
#
# CI/CD Examples:
#
#   # Option 1: GitHub Models (FREE - uses built-in GITHUB_TOKEN)
#   - name: Generate schema descriptions
#     run: ~/.claude/scripts/generate-schema-descriptions.sh --provider github
#
#   # Option 2: Anthropic API (requires secret)
#   - name: Generate schema descriptions
#     env:
#       ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
#     run: ~/.claude/scripts/generate-schema-descriptions.sh --provider anthropic
#
# GitHub Models supported model IDs:
#   - claude-sonnet-4-6 (mapped to AI21/etc on Azure - check availability)
#   - gpt-4o, gpt-4o-mini
#   - Meta-Llama-3.1-405B-Instruct
#   - Mistral-Large-2
#   See: https://github.com/marketplace/models

SNAPSHOT_DIR="/tmp/db-schema-sync"
PROVIDER=""
MODEL=""
MAX_TOKENS=4096
DRY_RUN=false

# Parse args
while [[ $# -gt 0 ]]; do
    case $1 in
        --snapshot-dir) SNAPSHOT_DIR="$2"; shift 2 ;;
        --provider) PROVIDER="$2"; shift 2 ;;
        --model) MODEL="$2"; shift 2 ;;
        --max-tokens) MAX_TOKENS="$2"; shift 2 ;;
        --dry-run) DRY_RUN=true; shift ;;
        *) shift ;;
    esac
done

PROMPT_FILE="${SNAPSHOT_DIR}/describe-prompt.json"
TEMPLATE_FILE="${SNAPSHOT_DIR}/descriptions-template.json"
OUTPUT_FILE="${SNAPSHOT_DIR}/descriptions.json"

# Validate inputs
if [[ ! -f "$PROMPT_FILE" ]]; then
    echo "Error: $PROMPT_FILE not found" >&2
    echo "Run: db-schema-sync.sh --json --describe first" >&2
    exit 1
fi

if [[ ! -f "$TEMPLATE_FILE" ]]; then
    echo "Error: $TEMPLATE_FILE not found" >&2
    exit 1
fi

#------------------------------------------------------------------------------
# Provider Detection & Configuration
#------------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=lib/yaml.sh
source "${SCRIPT_DIR}/lib/yaml.sh" || {
    echo "Error: Failed to load yaml.sh library" >&2
    exit 1
}

# Auto-detect provider if not specified
if [[ -z "$PROVIDER" ]]; then
    if [[ -n "${GITHUB_ACTIONS:-}" && -n "${GITHUB_TOKEN:-}" ]]; then
        # Running in GitHub Actions with a token - use free GitHub Models
        PROVIDER="github"
    elif [[ -n "${ANTHROPIC_API_KEY:-}" ]]; then
        PROVIDER="anthropic"
    else
        # Try to resolve from secrets manager
        if [[ -f "${SCRIPT_DIR}/lib/project-config.sh" ]]; then
            source "${SCRIPT_DIR}/lib/project-config.sh" 2>/dev/null || true
            BACKEND=$(get_secrets_backend 2>/dev/null || echo "env")
            case "$BACKEND" in
                aws)
                    ANTHROPIC_API_KEY=$(aws secretsmanager get-secret-value \
                        --secret-id "ANTHROPIC_API_KEY" \
                        --query 'SecretString' --output text 2>/dev/null || echo "")
                    ;;
                infisical)
                    ANTHROPIC_API_KEY=$(infisical secrets get "ANTHROPIC_API_KEY" --plain 2>/dev/null || echo "")
                    ;;
            esac
        fi

        if [[ -n "${ANTHROPIC_API_KEY:-}" ]]; then
            PROVIDER="anthropic"
        elif [[ -n "${GITHUB_TOKEN:-}" ]]; then
            PROVIDER="github"
        else
            echo "Error: No API credentials found" >&2
            echo "" >&2
            echo "Options:" >&2
            echo "  1. GitHub Models (free in Actions): set GITHUB_TOKEN or use --provider github" >&2
            echo "  2. Anthropic API: set ANTHROPIC_API_KEY" >&2
            echo "  3. Secrets manager: configure in PROJECT.yaml" >&2
            exit 1
        fi
    fi
fi

# Resolve model
if [[ -z "$MODEL" ]]; then
    if [[ -f "PROJECT.yaml" ]]; then
        MODEL=$(yaml_get '.schema_sync.auto_describe.model // ""' PROJECT.yaml)
    fi
fi

# Set provider-specific defaults
case "$PROVIDER" in
    github)
        API_URL="https://models.inference.ai.azure.com/chat/completions"
        API_KEY="${GITHUB_TOKEN:-}"

        if [[ -z "$API_KEY" ]]; then
            echo "Error: GITHUB_TOKEN not set (required for GitHub Models provider)" >&2
            exit 1
        fi

        # Map Anthropic model names to GitHub Models equivalents
        if [[ -z "$MODEL" || "$MODEL" == claude-* ]]; then
            # GitHub Models doesn't have Claude - use best available
            MODEL="gpt-4o"
            echo "Note: Using $MODEL via GitHub Models (free)" >&2
        fi
        ;;

    anthropic)
        API_URL="https://api.anthropic.com/v1/messages"
        API_KEY="${ANTHROPIC_API_KEY:-}"

        if [[ -z "$API_KEY" ]]; then
            echo "Error: ANTHROPIC_API_KEY not set" >&2
            exit 1
        fi

        [[ -z "$MODEL" ]] && MODEL="claude-sonnet-4-6"
        ;;

    *)
        echo "Error: Unknown provider '$PROVIDER' (use: anthropic, github)" >&2
        exit 1
        ;;
esac

#------------------------------------------------------------------------------
# Build Prompt
#------------------------------------------------------------------------------

# Read prompt data
ITEMS_COUNT=$(jq '.items_needing_descriptions' "$PROMPT_FILE")
SYSTEM_PROMPT=$(jq -r '.system_prompt' "$PROMPT_FILE")
DOMAIN_CONTEXT=$(jq -r '.domain_context // ""' "$PROMPT_FILE")

echo "Generating descriptions for $ITEMS_COUNT schema elements..."
echo "  Provider: $PROVIDER"
echo "  Model: $MODEL"

if [[ "$DRY_RUN" == true ]]; then
    echo "DRY RUN - would call $PROVIDER API"
    echo "  Items: $ITEMS_COUNT"
    echo "  Prompt file: $PROMPT_FILE"
    echo "  Template file: $TEMPLATE_FILE"
    exit 0
fi

# Build the user message
USER_MESSAGE=$(cat <<MSGEOF
I need you to generate descriptions for new database schema elements that were just deployed.

Here are the items that need descriptions:

$(jq -r '.items[] | "- [\(.type)] \(.database).\(.table)\(if .column then "." + .column else "" end) (\(if .type == "table" then "columns: " + .columns_summary else "type: " + .data_type end))"' "$PROMPT_FILE")

$(if [[ -n "$DOMAIN_CONTEXT" ]]; then echo "Domain context for reference:"; echo "$DOMAIN_CONTEXT"; fi)

Fill in descriptions for EVERY item below. Return ONLY valid JSON - no markdown, no code fences, no explanation.
Each description should be 1-2 sentences of plain English focused on business meaning, suitable for BI analysts.

Template to fill in:
$(cat "$TEMPLATE_FILE")
MSGEOF
)

#------------------------------------------------------------------------------
# Call API (provider-specific)
#------------------------------------------------------------------------------

call_anthropic_api() {
    curl -s -X POST "$API_URL" \
        -H "x-api-key: ${API_KEY}" \
        -H "anthropic-version: 2023-06-01" \
        -H "content-type: application/json" \
        -d "$(jq -n \
            --arg model "$MODEL" \
            --arg system "$SYSTEM_PROMPT" \
            --arg user "$USER_MESSAGE" \
            --arg max_tokens "$MAX_TOKENS" \
            '{
                model: $model,
                max_tokens: ($max_tokens | tonumber),
                system: $system,
                messages: [{role: "user", content: $user}]
            }')"
}

call_github_api() {
    curl -s -X POST "$API_URL" \
        -H "Authorization: Bearer ${API_KEY}" \
        -H "Content-Type: application/json" \
        -d "$(jq -n \
            --arg model "$MODEL" \
            --arg system "$SYSTEM_PROMPT" \
            --arg user "$USER_MESSAGE" \
            --arg max_tokens "$MAX_TOKENS" \
            '{
                model: $model,
                max_tokens: ($max_tokens | tonumber),
                messages: [
                    {role: "system", content: $system},
                    {role: "user", content: $user}
                ]
            }')"
}

RESPONSE=""
case "$PROVIDER" in
    anthropic) RESPONSE=$(call_anthropic_api) ;;
    github) RESPONSE=$(call_github_api) ;;
esac

#------------------------------------------------------------------------------
# Parse Response (provider-specific)
#------------------------------------------------------------------------------

RAW_TEXT=""
INPUT_TOKENS="unknown"
OUTPUT_TOKENS="unknown"

case "$PROVIDER" in
    anthropic)
        # Check for API errors
        if echo "$RESPONSE" | jq -e '.error' &>/dev/null; then
            echo "Error from Anthropic API:" >&2
            echo "$RESPONSE" | jq -r '.error.message // .error' >&2
            exit 1
        fi
        RAW_TEXT=$(echo "$RESPONSE" | jq -r '.content[0].text')
        INPUT_TOKENS=$(echo "$RESPONSE" | jq -r '.usage.input_tokens // "unknown"')
        OUTPUT_TOKENS=$(echo "$RESPONSE" | jq -r '.usage.output_tokens // "unknown"')
        ;;

    github)
        # Check for API errors
        if echo "$RESPONSE" | jq -e '.error' &>/dev/null; then
            echo "Error from GitHub Models API:" >&2
            echo "$RESPONSE" | jq -r '.error.message // .error' >&2
            exit 1
        fi
        RAW_TEXT=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')
        INPUT_TOKENS=$(echo "$RESPONSE" | jq -r '.usage.prompt_tokens // "unknown"')
        OUTPUT_TOKENS=$(echo "$RESPONSE" | jq -r '.usage.completion_tokens // "unknown"')
        ;;
esac

if [[ -z "$RAW_TEXT" || "$RAW_TEXT" == "null" ]]; then
    echo "Error: Empty response from API" >&2
    echo "Full response saved to ${SNAPSHOT_DIR}/describe-raw-response.json" >&2
    echo "$RESPONSE" > "${SNAPSHOT_DIR}/describe-raw-response.json"
    exit 1
fi

#------------------------------------------------------------------------------
# Validate & Save
#------------------------------------------------------------------------------

# Strip markdown code fences if present
CLEAN_JSON=$(echo "$RAW_TEXT" | sed -E 's/^```(json)?//; s/```$//' | sed '/^$/d')

# Validate JSON
if ! echo "$CLEAN_JSON" | jq '.' > /dev/null 2>&1; then
    echo "Warning: API returned invalid JSON, attempting to extract..." >&2
    # Try to find JSON array in the response
    CLEAN_JSON=$(echo "$RAW_TEXT" | tr '\n' ' ' | grep -oE '\[.*\]' | head -1)
    if ! echo "$CLEAN_JSON" | jq '.' > /dev/null 2>&1; then
        echo "Error: Could not parse API response as JSON" >&2
        echo "Raw response saved to ${SNAPSHOT_DIR}/describe-raw-response.txt" >&2
        echo "$RAW_TEXT" > "${SNAPSHOT_DIR}/describe-raw-response.txt"
        exit 1
    fi
fi

# Validate structure
EMPTY_COUNT=$(echo "$CLEAN_JSON" | jq '[.[] | select(.description == "" or .description == null)] | length')
TOTAL_COUNT=$(echo "$CLEAN_JSON" | jq 'length')

echo "$CLEAN_JSON" | jq '.' > "$OUTPUT_FILE"

echo ""
echo "Descriptions generated: ${OUTPUT_FILE}"
echo "  Total items: ${TOTAL_COUNT}"
echo "  Filled: $((TOTAL_COUNT - EMPTY_COUNT))"

if [[ "$EMPTY_COUNT" -gt 0 ]]; then
    echo "  Warning: ${EMPTY_COUNT} items still have empty descriptions"
fi

echo "  API usage: ${INPUT_TOKENS} input / ${OUTPUT_TOKENS} output tokens"
