#!/usr/bin/env bash
#
# init-project-config.sh - Initialize PROJECT.yaml configuration
#
# Usage:
#   init-project-config.sh [OPTIONS]
#
# Options:
#   --non-interactive      Skip prompts, use auto-detected values
#   --force                Overwrite existing PROJECT.yaml
#   --dry-run              Show what would be generated without writing
#   -h, --help             Show this help message

set -euo pipefail

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source required libraries
source "${SCRIPT_DIR}/lib/common.sh" || {
    echo "Error: Failed to load common.sh library" >&2
    exit 1
}

#------------------------------------------------------------------------------
# Configuration
#------------------------------------------------------------------------------

INTERACTIVE=true
FORCE=false
DRY_RUN=false
OUTPUT_FILE="PROJECT.yaml"

#------------------------------------------------------------------------------
# Functions
#------------------------------------------------------------------------------

show_help() {
    cat << EOF
init-project-config.sh - Initialize PROJECT.yaml configuration

Usage:
  init-project-config.sh [OPTIONS]

Options:
  --non-interactive      Skip prompts, use auto-detected values
  --force                Overwrite existing PROJECT.yaml
  --dry-run              Show what would be generated without writing
  -h, --help             Show this help message

Description:
  Generates a PROJECT.yaml configuration file by auto-detecting:
  - Project name
  - Programming languages and frameworks
  - Git platform and repository
  - Docker services and databases
  - Testing configuration

  In interactive mode, you can review and modify detected values.
  In non-interactive mode, all auto-detected values are used.

Examples:
  init-project-config.sh                    # Interactive mode
  init-project-config.sh --non-interactive  # Use all defaults
  init-project-config.sh --dry-run          # Preview without writing
EOF
}

auto_detect_config() {
    local -A config

    # Detect project name
    config[project_name]=$(basename "$(pwd)")

    # Detect languages using detect-tech-stack.sh
    if [[ -x "${SCRIPT_DIR}/detect-tech-stack.sh" ]]; then
        local languages
        languages=$("${SCRIPT_DIR}/detect-tech-stack.sh" json 2>/dev/null | python3 -c "import sys, json; print(' '.join(json.load(sys.stdin)['languages']))" 2>/dev/null || echo "")
        config[languages]="$languages"

        local frameworks
        frameworks=$("${SCRIPT_DIR}/detect-tech-stack.sh" json 2>/dev/null | python3 -c "import sys, json; print(' '.join(json.load(sys.stdin)['frameworks']))" 2>/dev/null || echo "")
        config[frameworks]="$frameworks"
    else
        config[languages]=""
        config[frameworks]=""
    fi

    # Detect git configuration
    local git_remote
    git_remote=$(git remote get-url origin 2>/dev/null || echo "")
    config[git_remote]="$git_remote"

    if [[ "$git_remote" =~ github\.com ]]; then
        config[git_platform]="github"
    elif [[ "$git_remote" =~ gitlab ]] || [[ "$git_remote" =~ git\. ]]; then
        config[git_platform]="gitlab"
    else
        config[git_platform]=""
    fi

    # Detect databases using detect-database.sh
    if [[ -x "${SCRIPT_DIR}/detect-database.sh" ]]; then
        local databases
        databases=$("${SCRIPT_DIR}/detect-database.sh" --json 2>/dev/null | python3 -c "import sys, json; data=json.load(sys.stdin); print(' '.join([d['type'] for d in data['databases']]))" 2>/dev/null || echo "")
        config[databases]="$databases"
    else
        config[databases]=""
    fi

    # Infer test command from languages
    if [[ "${config[languages]}" == *"python"* ]]; then
        config[test_command]="pytest"
    elif [[ "${config[languages]}" == *"nodejs"* ]]; then
        config[test_command]="npm test"
    else
        config[test_command]=""
    fi

    # Return config as key=value pairs
    for key in "${!config[@]}"; do
        echo "$key=${config[$key]}"
    done
}

generate_project_yaml() {
    local project_name="$1"
    local languages="$2"
    local frameworks="$3"
    local git_platform="$4"
    local git_remote="$5"
    local databases="$6"
    local test_command="$7"

    cat << EOF
# PROJECT.yaml - Project configuration
# Auto-generated by init-project-config.sh

project: ${project_name}

tech_stack:
  languages:
$(for lang in $languages; do echo "    - $lang"; done)
$(if [[ -n "$frameworks" ]]; then
  echo "  frameworks:"
  for fw in $frameworks; do echo "    - $fw"; done
fi)

git:
  platform: ${git_platform:-unknown}
  repo: ${git_remote:-}

ci:
  branches:
    staging: dev
    production: main

$(if [[ -n "$test_command" ]]; then
cat << TESTING
testing:
  command: ${test_command}
  min_coverage: 80
TESTING
fi)

$(if [[ -n "$databases" ]]; then
cat << DATABASES
databases:
$(for db in $databases; do
  echo "  - name: $db"
  echo "    migrations:"
  echo "      enabled: false"
done)
DATABASES
fi)

docker:
  registry:
    url: ""

secrets:
  backend: infisical
EOF
}

#------------------------------------------------------------------------------
# Argument Parsing
#------------------------------------------------------------------------------

while [[ $# -gt 0 ]]; do
    case "$1" in
        --non-interactive)
            INTERACTIVE=false
            shift
            ;;
        --force)
            FORCE=true
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            print_error "Unknown option: $1"
            show_help
            exit 1
            ;;
    esac
done

#------------------------------------------------------------------------------
# Main Logic
#------------------------------------------------------------------------------

# Check if PROJECT.yaml already exists
if [[ -f "$OUTPUT_FILE" ]] && [[ "$FORCE" != "true" ]] && [[ "$DRY_RUN" != "true" ]]; then
    print_error "PROJECT.yaml already exists. Use --force to overwrite."
    exit 1
fi

# Auto-detect configuration
print_info "Auto-detecting project configuration..."
declare -A detected_config
while IFS='=' read -r key value; do
    detected_config["$key"]="$value"
done < <(auto_detect_config)

# Show detected values
if [[ "$INTERACTIVE" == "true" ]] || [[ "$DRY_RUN" == "true" ]]; then
    print_info "Detected configuration:"
    echo "  Project: ${detected_config[project_name]}"
    echo "  Languages: ${detected_config[languages]:-none detected}"
    echo "  Frameworks: ${detected_config[frameworks]:-none detected}"
    echo "  Git platform: ${detected_config[git_platform]:-unknown}"
    echo "  Databases: ${detected_config[databases]:-none detected}"
    echo "  Test command: ${detected_config[test_command]:-none}"
    echo ""
fi

# In interactive mode, confirm before generating
if [[ "$INTERACTIVE" == "true" ]] && [[ "$DRY_RUN" != "true" ]]; then
    ask_yes_no "Generate PROJECT.yaml with these settings?" || {
        print_info "Cancelled"
        exit 0
    }
fi

# Generate PROJECT.yaml
yaml_content=$(generate_project_yaml \
    "${detected_config[project_name]}" \
    "${detected_config[languages]}" \
    "${detected_config[frameworks]}" \
    "${detected_config[git_platform]}" \
    "${detected_config[git_remote]}" \
    "${detected_config[databases]}" \
    "${detected_config[test_command]}")

# Output or write
if [[ "$DRY_RUN" == "true" ]]; then
    print_info "Generated PROJECT.yaml (dry-run):"
    echo ""
    echo "$yaml_content"
else
    echo "$yaml_content" > "$OUTPUT_FILE"
    print_success "Generated $OUTPUT_FILE"
    print_info "Review and customize as needed"
fi
